### ISSUE TITLE
Increase paging and aggregation count for geometries 

### ISSUE THREAD

**Issue by one-github** [geoadmin/mf-chsdi3#3194]
**Situation**
Request by @one-github

> We need to count current inhabitant numbers for a given geometry on the layer `ch.bfs.volkszaehlung-bevoelkerungsstatistik_einwohner`. The scenario is: During an emergency situation crisis response staff need to find out how many people need to be evacuated in a given area.
> 
> Currently the 'identify' service returns multiple data sets (including past census data) for every 100m x 100m rectangle in the geometry. Combined with the current 200 items response limit on the v3 API this currently does not even work for small villages. Past census data is also not of interest in this scenario.
> 
> Sample Request with current API:
> `https://api3.geo.admin.ch/rest/services/ech/MapServer/identify?geometry=2573255.6,1204985.25,2575785.6,1207335.25&geometryFormat=geojson&geometryType=esriGeometryEnvelope&imageDisplay=1920%2C852%2C96&layers=all%3Ach.bfs.volkszaehlung-bevoelkerungsstatistik_einwohner&mapExtent=2420000%2C1350000%2C2900000%2C1030000&tolerance=0&returnGeometry=false&sr=2056`
> 
> Current response:
> `{
>   "results": [{
>       "featureId": 7277217,
>       "layerBodId": "ch.bfs.volkszaehlung-bevoelkerungsstatistik_einwohner",
>       "layerName": "Bev\u00f6lkerung (Einwohner)",
>       "id": 7277217,
>       "properties": {
>         "i_year": 2017,
>         "reli": 57572054,
>         "number": 6,
>         "label": 57572054
>       }
>     },
>     {
>       "featureId": 4551876,
>       "layerBodId": "ch.bfs.volkszaehlung-bevoelkerungsstatistik_einwohner",
>       "layerName": "Bev\u00f6lkerung (Einwohner)",
>       "id": 4551876,
>       "properties": {
>         "i_year": 2000,
>         "reli": 57572054,
>         "number": 3,
>         "label": 57572054
>       }
>     }
>     ...
>   ]
> }`
> 
> Hence we propose a new function called 'sumUp=latest'. It will sum up latest census data for each 100m x 100m rectangle
> 
> Further enhancements could be made by defining additional values for the parameter 'sumUp' in the future.
> 
> Proposed API call for this scenario:
> `https://api3.geo.admin.ch/rest/services/ech/MapServer/identify?geometry=2573255.6,1204985.25,2575785.6,1207335.25&geometryFormat=geojson&geometryType=esriGeometryEnvelope&imageDisplay=1920%2C852%2C96&layers=all%3Ach.bfs.volkszaehlung-bevoelkerungsstatistik_einwohner&mapExtent=2420000%2C1350000%2C2900000%2C1030000&tolerance=0&returnGeometry=false&sr=2056&sumUp=latest`
> 
> Proposed reponse:
> `{
>       "layerBodId": "ch.bfs.volkszaehlung-bevoelkerungsstatistik_einwohner",
>       "layerName": "Bev\u00f6lkerung (Einwohner)",
>       "properties": {
>         "i_year": "latest",
>         "number": 612345
>       }
> }`
> 
> Thanks!

**Task:**
- allow more  than 200 results.
- decision if aggregation/sum  is in accordance with eCh /ogc/esri api
- timeline

**Action**

- [ ]  allow more  than 200 results in paging: set limit 10'000 (should be enough -> @procrastinatio 
wontfix --> Is this really needed? The user can loop through the objects with the parameter "offset" of the "Identity Service". In order for the user to know how many loops to do, we should provide the number of features in the layer, e.g. in the "Layers Metadata" service.
- [ ]  Check  if aggregation/sum  is in accordance with ech /ogc/esri api @p1d1d1 
wontfix --> "time" parameter + "data manipulation" client side.
- [ ]  if compliance confirmed  Add attribute in service by @procrastinatio 
wontfix --> 

**Result**
- paging increased
- Aggregation possible if compliant with standards
- in production end of q2 2019

**Comment by davidoesch** [comment]
@p1d1d1 can you give a review regarding accordance with ech /ogc/esri api?
@procrastinatio  work estimate in days for you?

**Comment by AFoletti** [comment]
As a partial solution: use "timeInstant=YYYY" to limit the results to a specific year.
[Example](https://api3.geo.admin.ch/rest/services/all/MapServer/identify?geometry=2614496.0003662105,1191871.9998779297&geometryFormat=geojson&geometryType=esriGeometryPoint&imageDisplay=1536,294,96&lang=en&layers=all:ch.bfs.volkszaehlung-bevoelkerungsstatistik_einwohner&limit=10&mapExtent=2606800.9016627786,1189200.4013794698,2637520.9016627786,1195080.4013794698&returnGeometry=true&sr=2056&timeInstant=2012&tolerance=10)

**Comment by one-github** [comment]
> As a partial solution: use "timeInstant=YYYY" to limit the results to a specific year.
> [Example](https://api3.geo.admin.ch/rest/services/all/MapServer/identify?geometry=2614496.0003662105,1191871.9998779297&geometryFormat=geojson&geometryType=esriGeometryPoint&imageDisplay=1536,294,96&lang=en&layers=all:ch.bfs.volkszaehlung-bevoelkerungsstatistik_einwohner&limit=10&mapExtent=2606800.9016627786,1189200.4013794698,2637520.9016627786,1195080.4013794698&returnGeometry=true&sr=2056&timeInstant=2012&tolerance=10)

Good idea, however: Is the census data set for a given year complete? Looking at the full response from the service I got the impression that there was only older census data available for a significant portion of the 100m x 100m rectangles.

**Comment by AFoletti** [comment]
> Good idea, however: Is the census data set for a given year complete? Looking at the full response from the service I got the impression that there was only older census data available for a significant portion of the 100m x 100m rectangles.

Because of the 200 limit and the fact that the output is not ordered it is difficult to judge the "completeness" of the dataset based on an identify result.
Anyways: yes, the dataset is complete for every year at disposal, where "complete==the full delivered dataset". For more info about the dataset production you should contact the responsible office.

**Comment by p1d1d1** [comment]
@AFoletti where does the parameter "timeInstant" come from?

**Comment by AFoletti** [comment]
@p1d1d1 ~~from the API docum...~~ no, it does not...
Uhm, I might have mentioned an undocumented capability of our API... my bad 🙄

**Comment by p1d1d1** [comment]
@AFoletti i don't see any "timeInstant" parameter in ESRI REST.
By the way @davidoesch I would proceed as suggested by @AFoletti. With the "time" parameter the result is limited to a specific year, then "data manipulation" is done client side.

**Comment by procrastinatio** [comment]
We never implemented the infamous ArcGIS REST API in geoadmin API3, we just used it as an inspiration.
Back in 2014, I did make some compatibility test. This used to work: http://www.procrastinatio.org/2014/11/24/esri-identify/ (ESRI Identify), but it was never an explicit goal back then.

By the way, 80% of the API is not documented outside the source code.

**Comment by davidoesch** [comment]
Decision "With the "time" parameter the result is limited to a specific year, then "data manipulation" is done client side."

-> @procastrinatio effort estimate?

**Comment by p1d1d1** [comment]
IMHO we don't need any action here. 

> Action
> - [ ] allow more than 200 results in paging: set limit 10'000 (should be enough -> @procrastinatio

Is this really needed? The user can loop through the objects with the parameter "offset" of the "Identity Service". In order for the user to know how many loops to do, we should provide the number of features in the layer, e.g. in the "Layers Metadata" service.

> - [ ] Check if aggregation/sum is in accordance with ech /ogc/esri api @p1d1d1
As said --> "time" parameter + "data manipulation" client side.

**Comment by davidoesch** [comment]
@one-github :"The user can loop through the objects with the parameter "offset" of the "Identity Service". " good enough for you? or do you need an explicit number of features?

**Comment by one-github** [comment]
@davidoesch I have my doubts about scalability / performance, since it can possibly mean 100s of requests to the "Identify Service" for one user query. I will write a small PoC based on this implementation idea and let our team test it. Thanks for your help, will report results here around end of June.

**Comment by procrastinatio** [comment]
With paging (`offset`), you may download any dataset which has a tooltip. You just have to loop over results.

**Comment by one-github** [comment]
We came across a strange behavior of the API during the implementation of the use case described in my first post.

When we query a small polygon on the layer `ch.bfs.volkszaehlung-bevoelkerungsstatistik_einwohner` we get a specific result (which seems OK):

[https://api3.geo.admin.ch/rest/services/ech/MapServer/identify with small area](https://api3.geo.admin.ch/rest/services/ech/MapServer/identify?geometry=%7B%22paths%22:%5B%5B%5B2554164,1198466%5D,%5B2554164,1198474%5D,%5B2554157,1198474%5D,%5B2554157,1198466%5D,%5B2554164,1198466%5D%5D%5D%7D&geometryType=esriGeometryPolygon&imageDisplay=1920%2C852%2C96&mapExtent=420000%2C350000%2C900000%2C30000&returnGeometry=false&sr=2056&tolerance=0&layers=all%3Ach.bfs.volkszaehlung-bevoelkerungsstatistik_einwohner)

```
geometry: {
    "paths": [
        [
            [2554164, 1198466],
            [2554164, 1198474],
            [2554157, 1198474],
            [2554157, 1198466],
            [2554164, 1198466]
        ]
    ]
}
geometryType: esriGeometryPolygon
imageDisplay: 1920,852,96
mapExtent: 420000,350000,900000,30000
returnGeometry: false
sr: 2056
tolerance: 0
layers: all:ch.bfs.volkszaehlung-bevoelkerungsstatistik_einwohner
```

```
{"results": [{"featureId": 7307078, "attributes": {"i_year": 2017, "reli": 55411984, "number": 3, "label": 55411984}, "layerBodId": "ch.bfs.volkszaehlung-bevoelkerungsstatistik_einwohner", "layerName": "Bev\u00f6lkerung (Einwohner)", "id": 7307078}, {"featureId": 6963007, "attributes": {"i_year": 2016, "reli": 55411984, "number": 3, "label": 55411984}, "layerBodId": "ch.bfs.volkszaehlung-bevoelkerungsstatistik_einwohner", "layerName": "Bev\u00f6lkerung (Einwohner)", "id": 6963007}, {"featureId": 6619913, "attributes": {"i_year": 2015, "reli": 55411984, "number": 3, "label": 55411984}, "layerBodId": "ch.bfs.volkszaehlung-bevoelkerungsstatistik_einwohner", "layerName": "Bev\u00f6lkerung (Einwohner)", "id": 6619913}, {"featureId": 6277511, "attributes": {"i_year": 2014, "reli": 55411984, "number": 3, "label": 55411984}, "layerBodId": "ch.bfs.volkszaehlung-bevoelkerungsstatistik_einwohner", "layerName": "Bev\u00f6lkerung (Einwohner)", "id": 6277511}, {"featureId": 5935832, "attributes": {"i_year": 2013, "reli": 55411984, "number": 3, "label": 55411984}, "layerBodId": "ch.bfs.volkszaehlung-bevoelkerungsstatistik_einwohner", "layerName": "Bev\u00f6lkerung (Einwohner)", "id": 5935832}, {"featureId": 5595015, "attributes": {"i_year": 2012, "reli": 55411984, "number": 3, "label": 55411984}, "layerBodId": "ch.bfs.volkszaehlung-bevoelkerungsstatistik_einwohner", "layerName": "Bev\u00f6lkerung (Einwohner)", "id": 5595015}, {"featureId": 5255312, "attributes": {"i_year": 2011, "reli": 55411984, "number": 3, "label": 55411984}, "layerBodId": "ch.bfs.volkszaehlung-bevoelkerungsstatistik_einwohner", "layerName": "Bev\u00f6lkerung (Einwohner)", "id": 5255312}, {"featureId": 4916072, "attributes": {"i_year": 2010, "reli": 55411984, "number": 3, "label": 55411984}, "layerBodId": "ch.bfs.volkszaehlung-bevoelkerungsstatistik_einwohner", "layerName": "Bev\u00f6lkerung (Einwohner)", "id": 4916072}, {"featureId": 4578971, "attributes": {"i_year": 2000, "reli": 55411984, "number": 3, "label": 55411984}, "layerBodId": "ch.bfs.volkszaehlung-bevoelkerungsstatistik_einwohner", "layerName": "Bev\u00f6lkerung (Einwohner)", "id": 4578971}]}
```

Now when we enlarge the area for some 100m on each side, the result is suddenly empty:

[https://api3.geo.admin.ch/rest/services/ech/MapServer/identify with larger area](https://api3.geo.admin.ch/rest/services/ech/MapServer/identify?geometry=%7B%22paths%22:%5B%5B%5B2554060,1198340%5D,%5B2554060,1198530%5D,%5B2554240,1198530%5D,%5B2554240,1198340%5D,%5B2554060,1198340%5D%5D%5D%7D&geometryType=esriGeometryPolygon&imageDisplay=1920%2C852%2C96&mapExtent=420000%2C350000%2C900000%2C30000&returnGeometry=false&sr=2056&tolerance=0&layers=all%3Ach.bfs.volkszaehlung-bevoelkerungsstatistik_einwohner)

```
geometry: {
    "paths": [
        [
            [2554060, 1198340],
            [2554060, 1198530],
            [2554240, 1198530],
            [2554240, 1198340],
            [2554060, 1198340]
        ]
    ]
}
geometryType: esriGeometryPolygon
imageDisplay: 1920,852,96
mapExtent: 420000,350000,900000,30000
returnGeometry: false
sr: 2056
tolerance: 0
layers: all:ch.bfs.volkszaehlung-bevoelkerungsstatistik_einwohner
```

`{"results": []}`

What's the reason for this? Thanks!

**Comment by danduk82** [comment]
@boecklic could you please have a look?

**Comment by one-github** [comment]
What's the status on this?

**Comment by procrastinatio** [comment]
I guess we never really used `identify` with geometries other than `esriGeometryPoint` and `esriGeometryEnvelope`. So for now, stick with `esriGeometryEnvelope` which seems to works.

**Geometry check**
https://s.geo.admin.ch/8426f43eed

**big area**
https://api3.geo.admin.ch/rest/services/ech/MapServer/identify?geometry=2554060,1198340,2554240,1198530&geometryType=esriGeometryEnvelope&imageDisplay=1920,852,96&mapExtent=420000,350000,900000,30000&returnGeometry=false&sr=2056&tolerance=0&layers=all:ch.bfs.volkszaehlung-bevoelkerungsstatistik_einwohner

**small area**
https://api3.geo.admin.ch/rest/services/ech/MapServer/identify?geometry=2554157,1198466,2554164,1198474&geometryType=esriGeometryEnvelope&imageDisplay=1920,852,96&mapExtent=420000,350000,900000,30000&returnGeometry=false&sr=2056&tolerance=0&layers=all:ch.bfs.volkszaehlung-bevoelkerungsstatistik_einwohner

**Comment by one-github** [comment]
Does that mean polygons don't work with the identify service at the moment?

**Comment by procrastinatio** [comment]
I have to check.

**Comment by procrastinatio** [comment]
With `esriGeometryPolygon` the keyword is `rings` not `paths`, which is for `esriGeometryPolyline`. In the first case, the polyline is touching the geometry, so we get a hit, in the second case, it is completely outside, so no hit. I will check that the given geometry is of the type passed as argument.

**Comment by one-github** [comment]
We'll check on that!

**Comment by one-github** [comment]
That was it, thanks @procrastinatio!

The following requests now work as the should, ie. giving back the same result:

https://api3.geo.admin.ch/rest/services/ech/MapServer/identify?geometry=%7B%22rings%22:%5B%5B%5B2554060,1198340%5D,%5B2554060,1198530%5D,%5B2554240,1198530%5D,%5B2554240,1198340%5D,%5B2554060,1198340%5D%5D%5D%7D&geometryType=esriGeometryPolygon&imageDisplay=1920%2C852%2C96&mapExtent=420000%2C350000%2C900000%2C30000&returnGeometry=false&sr=2056&tolerance=0&layers=all%3Ach.bfs.volkszaehlung-bevoelkerungsstatistik_einwohner

https://api3.geo.admin.ch/rest/services/ech/MapServer/identify?geometry=%7B%22rings%22:%5B%5B%5B2554164,1198466%5D,%5B2554164,1198474%5D,%5B2554157,1198474%5D,%5B2554157,1198466%5D,%5B2554164,1198466%5D%5D%5D%7D&geometryType=esriGeometryPolygon&imageDisplay=1920%2C852%2C96&mapExtent=420000%2C350000%2C900000%2C30000&returnGeometry=false&sr=2056&tolerance=0&layers=all%3Ach.bfs.volkszaehlung-bevoelkerungsstatistik_einwohner

**Comment by procrastinatio** [comment]
Apparently, it is solved
